import type { Metadata } from 'next';

import TopLayout from '../component/baseLayout/top';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ko">
            <body className="">
                <TopLayout />
                {/* --- Main Content 영역 (page.tsx가 들어오는 곳) --- */}

                {/* min-h-screen으로 최소 높이를 확보하여 Footer가 아래에 붙도록 합니다. */}
                {children}
                <div className={'text-3xl font-bold'}> Test</div>

                {/* --- Footer 영역 --- */}
                <footer className=""></footer>
            </body>
        </html>
    );
}
